config/routes.rb
Rails.application.routes.draw do
  get 'session/new'

  get 'session/create'

  get 'session/destroy'

  get 'raiz/index'

  resources :archivo_hitos

  resources :archivo_tareas

  resources :archivo_listtareas

  resources :archivo_proyectos

  resources :user_hitos

  resources :user_tareas

  resources :user_listtareas

  resources :user_proyectos

  resources :archivos

  resources :users

  resources :hitos

  resources :tareas

  resources :listtareas

  resources :proyectos

  resources :empresas

  root 'raiz#index'

end

app/models/archivo.rb
class Archivo < ActiveRecord::Base
end

app/models/archivo_hito.rb
class ArchivoHito < ActiveRecord::Base
end

app/models/archivo_proyecto.rb
class ArchivoProyecto < ActiveRecord::Base
end

app/models/archivo_tarea.rb
class ArchivoTarea < ActiveRecord::Base
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
end

app/models/hito.rb
class Hito < ActiveRecord::Base
end

app/models/listtarea.rb
class Listtarea < ActiveRecord::Base
end

app/models/proyecto.rb
class Proyecto < ActiveRecord::Base
end

app/models/tarea.rb
class Tarea < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

	validate :email, presence: true, uniqueness: true


  	has_secure_password
end

app/models/user_hito.rb
class UserHito < ActiveRecord::Base
end

app/models/user_listtarea.rb
class UserListtarea < ActiveRecord::Base
end

app/models/user_proyecto.rb
class UserProyecto < ActiveRecord::Base
end

app/models/user_tarea.rb
class UserTarea < ActiveRecord::Base
end

app/controllers/user_hitos_controller.rb
class UserHitosController < ApplicationController
  before_action :set_user_hito, only: [:show, :edit, :update, :destroy]

  # GET /user_hitos
  # GET /user_hitos.json
  def index
    @user_hitos = UserHito.all
  end

  # GET /user_hitos/1
  # GET /user_hitos/1.json
  def show
  end

  # GET /user_hitos/new
  def new
    @user_hito = UserHito.new
  end

  # GET /user_hitos/1/edit
  def edit
  end

  # POST /user_hitos
  # POST /user_hitos.json
  def create
    @user_hito = UserHito.new(user_hito_params)

    respond_to do |format|
      if @user_hito.save
        format.html { redirect_to @user_hito, notice: 'User hito was successfully created.' }
        format.json { render :show, status: :created, location: @user_hito }
      else
        format.html { render :new }
        format.json { render json: @user_hito.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_hitos/1
  # PATCH/PUT /user_hitos/1.json
  def update
    respond_to do |format|
      if @user_hito.update(user_hito_params)
        format.html { redirect_to @user_hito, notice: 'User hito was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_hito }
      else
        format.html { render :edit }
        format.json { render json: @user_hito.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_hitos/1
  # DELETE /user_hitos/1.json
  def destroy
    @user_hito.destroy
    respond_to do |format|
      format.html { redirect_to user_hitos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_hito
      @user_hito = UserHito.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_hito_params
      params.require(:user_hito).permit(:user_id, :hito_id)
    end
end

app/helpers/archivos_helper.rb
module ArchivosHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/hitos_helper.rb
module HitosHelper
end

app/helpers/raiz_helper.rb
module RaizHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/tareas_helper.rb
module TareasHelper
end

app/helpers/user_hitos_helper.rb
module UserHitosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user_hitos/_form.html.erb
<%= form_for(@user_hito) do |f| %>
  <% if @user_hito.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_hito.errors.count, "error") %> prohibited this user_hito from being saved:</h2>

      <ul>
      <% @user_hito.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :hito_id %><br>
    <%= f.number_field :hito_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_hitos/edit.html.erb
<h1>Editing user_hito</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_hito %> |
<%= link_to 'Back', user_hitos_path %>

app/views/user_hitos/index.html.erb
<h1>Listing user_hitos</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Hito</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_hitos.each do |user_hito| %>
      <tr>
        <td><%= user_hito.user_id %></td>
        <td><%= user_hito.hito_id %></td>
        <td><%= link_to 'Show', user_hito %></td>
        <td><%= link_to 'Edit', edit_user_hito_path(user_hito) %></td>
        <td><%= link_to 'Destroy', user_hito, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User hito', new_user_hito_path %>

app/views/user_hitos/new.html.erb
<h1>New user_hito</h1>

<%= render 'form' %>

<%= link_to 'Back', user_hitos_path %>

app/views/user_hitos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_hito.user_id %>
</p>

<p>
  <strong>Hito:</strong>
  <%= @user_hito.hito_id %>
</p>

<%= link_to 'Edit', edit_user_hito_path(@user_hito) %> |
<%= link_to 'Back', user_hitos_path %>