config/routes.rb
Rails.application.routes.draw do
  get 'session/new'

  get 'session/create'

  get 'session/destroy'

  get 'raiz/index'

  resources :archivo_hitos

  resources :archivo_tareas

  resources :archivo_listtareas

  resources :archivo_proyectos

  resources :user_hitos

  resources :user_tareas

  resources :user_listtareas

  resources :user_proyectos

  resources :archivos

  resources :users

  resources :hitos

  resources :tareas

  resources :listtareas

  resources :proyectos

  resources :empresas

  root 'raiz#index'

end

app/models/archivo.rb
class Archivo < ActiveRecord::Base
end

app/models/archivo_hito.rb
class ArchivoHito < ActiveRecord::Base
end

app/models/archivo_proyecto.rb
class ArchivoProyecto < ActiveRecord::Base
end

app/models/archivo_tarea.rb
class ArchivoTarea < ActiveRecord::Base
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
end

app/models/hito.rb
class Hito < ActiveRecord::Base
end

app/models/listtarea.rb
class Listtarea < ActiveRecord::Base
end

app/models/proyecto.rb
class Proyecto < ActiveRecord::Base
end

app/models/tarea.rb
class Tarea < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

	validate :email, presence: true, uniqueness: true


  	has_secure_password
end

app/models/user_hito.rb
class UserHito < ActiveRecord::Base
end

app/models/user_listtarea.rb
class UserListtarea < ActiveRecord::Base
end

app/models/user_proyecto.rb
class UserProyecto < ActiveRecord::Base
end

app/models/user_tarea.rb
class UserTarea < ActiveRecord::Base
end

app/controllers/archivo_hitos_controller.rb
class ArchivoHitosController < ApplicationController
  before_action :set_archivo_hito, only: [:show, :edit, :update, :destroy]

  # GET /archivo_hitos
  # GET /archivo_hitos.json
  def index
    @archivo_hitos = ArchivoHito.all
  end

  # GET /archivo_hitos/1
  # GET /archivo_hitos/1.json
  def show
  end

  # GET /archivo_hitos/new
  def new
    @archivo_hito = ArchivoHito.new
  end

  # GET /archivo_hitos/1/edit
  def edit
  end

  # POST /archivo_hitos
  # POST /archivo_hitos.json
  def create
    @archivo_hito = ArchivoHito.new(archivo_hito_params)

    respond_to do |format|
      if @archivo_hito.save
        format.html { redirect_to @archivo_hito, notice: 'Archivo hito was successfully created.' }
        format.json { render :show, status: :created, location: @archivo_hito }
      else
        format.html { render :new }
        format.json { render json: @archivo_hito.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /archivo_hitos/1
  # PATCH/PUT /archivo_hitos/1.json
  def update
    respond_to do |format|
      if @archivo_hito.update(archivo_hito_params)
        format.html { redirect_to @archivo_hito, notice: 'Archivo hito was successfully updated.' }
        format.json { render :show, status: :ok, location: @archivo_hito }
      else
        format.html { render :edit }
        format.json { render json: @archivo_hito.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /archivo_hitos/1
  # DELETE /archivo_hitos/1.json
  def destroy
    @archivo_hito.destroy
    respond_to do |format|
      format.html { redirect_to archivo_hitos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_archivo_hito
      @archivo_hito = ArchivoHito.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def archivo_hito_params
      params.require(:archivo_hito).permit(:archivo_id, :hito_id)
    end
end

app/helpers/archivo_hitos_helper.rb
module ArchivoHitosHelper
end

app/helpers/archivos_helper.rb
module ArchivosHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/hitos_helper.rb
module HitosHelper
end

app/helpers/raiz_helper.rb
module RaizHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/tareas_helper.rb
module TareasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/archivo_hitos/_form.html.erb
<%= form_for(@archivo_hito) do |f| %>
  <% if @archivo_hito.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@archivo_hito.errors.count, "error") %> prohibited this archivo_hito from being saved:</h2>

      <ul>
      <% @archivo_hito.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :archivo_id %><br>
    <%= f.number_field :archivo_id %>
  </div>
  <div class="field">
    <%= f.label :hito_id %><br>
    <%= f.number_field :hito_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/archivo_hitos/edit.html.erb
<h1>Editing archivo_hito</h1>

<%= render 'form' %>

<%= link_to 'Show', @archivo_hito %> |
<%= link_to 'Back', archivo_hitos_path %>

app/views/archivo_hitos/index.html.erb
<h1>Listing archivo_hitos</h1>

<table>
  <thead>
    <tr>
      <th>Archivo</th>
      <th>Hito</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @archivo_hitos.each do |archivo_hito| %>
      <tr>
        <td><%= archivo_hito.archivo_id %></td>
        <td><%= archivo_hito.hito_id %></td>
        <td><%= link_to 'Show', archivo_hito %></td>
        <td><%= link_to 'Edit', edit_archivo_hito_path(archivo_hito) %></td>
        <td><%= link_to 'Destroy', archivo_hito, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Archivo hito', new_archivo_hito_path %>

app/views/archivo_hitos/new.html.erb
<h1>New archivo_hito</h1>

<%= render 'form' %>

<%= link_to 'Back', archivo_hitos_path %>

app/views/archivo_hitos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Archivo:</strong>
  <%= @archivo_hito.archivo_id %>
</p>

<p>
  <strong>Hito:</strong>
  <%= @archivo_hito.hito_id %>
</p>

<%= link_to 'Edit', edit_archivo_hito_path(@archivo_hito) %> |
<%= link_to 'Back', archivo_hitos_path %>