config/routes.rb
Rails.application.routes.draw do
  get 'session/new'

  get 'session/create'

  get 'session/destroy'

  get 'raiz/index'

  resources :archivo_hitos

  resources :archivo_tareas

  resources :archivo_listtareas

  resources :archivo_proyectos

  resources :user_hitos

  resources :user_tareas

  resources :user_listtareas

  resources :user_proyectos

  resources :archivos

  resources :users

  resources :hitos

  resources :tareas

  resources :listtareas

  resources :proyectos

  resources :empresas

  root 'raiz#index'

end

app/models/archivo.rb
class Archivo < ActiveRecord::Base
end

app/models/archivo_hito.rb
class ArchivoHito < ActiveRecord::Base
end

app/models/archivo_proyecto.rb
class ArchivoProyecto < ActiveRecord::Base
end

app/models/archivo_tarea.rb
class ArchivoTarea < ActiveRecord::Base
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
end

app/models/hito.rb
class Hito < ActiveRecord::Base
end

app/models/listtarea.rb
class Listtarea < ActiveRecord::Base
end

app/models/proyecto.rb
class Proyecto < ActiveRecord::Base
end

app/models/tarea.rb
class Tarea < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

	validate :email, presence: true, uniqueness: true


  	has_secure_password
end

app/models/user_hito.rb
class UserHito < ActiveRecord::Base
end

app/models/user_listtarea.rb
class UserListtarea < ActiveRecord::Base
end

app/models/user_proyecto.rb
class UserProyecto < ActiveRecord::Base
end

app/models/user_tarea.rb
class UserTarea < ActiveRecord::Base
end

app/controllers/hitos_controller.rb
class HitosController < ApplicationController
  before_action :set_hito, only: [:show, :edit, :update, :destroy]

  # GET /hitos
  # GET /hitos.json
  def index
    @hitos = Hito.all
  end

  # GET /hitos/1
  # GET /hitos/1.json
  def show
  end

  # GET /hitos/new
  def new
    @hito = Hito.new
  end

  # GET /hitos/1/edit
  def edit
  end

  # POST /hitos
  # POST /hitos.json
  def create
    @hito = Hito.new(hito_params)

    respond_to do |format|
      if @hito.save
        format.html { redirect_to @hito, notice: 'Hito was successfully created.' }
        format.json { render :show, status: :created, location: @hito }
      else
        format.html { render :new }
        format.json { render json: @hito.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hitos/1
  # PATCH/PUT /hitos/1.json
  def update
    respond_to do |format|
      if @hito.update(hito_params)
        format.html { redirect_to @hito, notice: 'Hito was successfully updated.' }
        format.json { render :show, status: :ok, location: @hito }
      else
        format.html { render :edit }
        format.json { render json: @hito.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hitos/1
  # DELETE /hitos/1.json
  def destroy
    @hito.destroy
    respond_to do |format|
      format.html { redirect_to hitos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hito
      @hito = Hito.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hito_params
      params.require(:hito).permit(:proyecto_id, :nombre, :description, :falta, :ffin, :responsable_id, :thito, :ehito, :privada)
    end
end

app/helpers/archivos_helper.rb
module ArchivosHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/hitos_helper.rb
module HitosHelper
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/helpers/raiz_helper.rb
module RaizHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/tareas_helper.rb
module TareasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hitos/_form.html.erb
<%= form_for(@hito) do |f| %>
  <% if @hito.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hito.errors.count, "error") %> prohibited this hito from being saved:</h2>

      <ul>
      <% @hito.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :proyecto_id %><br>
    <%= f.number_field :proyecto_id %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :falta %><br>
    <%= f.datetime_select :falta %>
  </div>
  <div class="field">
    <%= f.label :ffin %><br>
    <%= f.datetime_select :ffin %>
  </div>
  <div class="field">
    <%= f.label :responsable_id %><br>
    <%= f.number_field :responsable_id %>
  </div>
  <div class="field">
    <%= f.label :thito %><br>
    <%= f.number_field :thito %>
  </div>
  <div class="field">
    <%= f.label :ehito %><br>
    <%= f.number_field :ehito %>
  </div>
  <div class="field">
    <%= f.label :privada %><br>
    <%= f.number_field :privada %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hitos/edit.html.erb
<h1>Editing hito</h1>

<%= render 'form' %>

<%= link_to 'Show', @hito %> |
<%= link_to 'Back', hitos_path %>

app/views/hitos/index.html.erb
<h1>Listing hitos</h1>

<table>
  <thead>
    <tr>
      <th>Proyecto</th>
      <th>Nombre</th>
      <th>Description</th>
      <th>Falta</th>
      <th>Ffin</th>
      <th>Responsable</th>
      <th>Thito</th>
      <th>Ehito</th>
      <th>Privada</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hitos.each do |hito| %>
      <tr>
        <td><%= hito.proyecto_id %></td>
        <td><%= hito.nombre %></td>
        <td><%= hito.description %></td>
        <td><%= hito.falta %></td>
        <td><%= hito.ffin %></td>
        <td><%= hito.responsable_id %></td>
        <td><%= hito.thito %></td>
        <td><%= hito.ehito %></td>
        <td><%= hito.privada %></td>
        <td><%= link_to 'Show', hito %></td>
        <td><%= link_to 'Edit', edit_hito_path(hito) %></td>
        <td><%= link_to 'Destroy', hito, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hito', new_hito_path %>

app/views/hitos/new.html.erb
<h1>New hito</h1>

<%= render 'form' %>

<%= link_to 'Back', hitos_path %>

app/views/hitos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Proyecto:</strong>
  <%= @hito.proyecto_id %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @hito.nombre %>
</p>

<p>
  <strong>Description:</strong>
  <%= @hito.description %>
</p>

<p>
  <strong>Falta:</strong>
  <%= @hito.falta %>
</p>

<p>
  <strong>Ffin:</strong>
  <%= @hito.ffin %>
</p>

<p>
  <strong>Responsable:</strong>
  <%= @hito.responsable_id %>
</p>

<p>
  <strong>Thito:</strong>
  <%= @hito.thito %>
</p>

<p>
  <strong>Ehito:</strong>
  <%= @hito.ehito %>
</p>

<p>
  <strong>Privada:</strong>
  <%= @hito.privada %>
</p>

<%= link_to 'Edit', edit_hito_path(@hito) %> |
<%= link_to 'Back', hitos_path %>