config/routes.rb
Rails.application.routes.draw do
  get 'session/new'

  get 'session/create'

  get 'session/destroy'

  get 'raiz/index'

  resources :archivo_hitos

  resources :archivo_tareas

  resources :archivo_listtareas

  resources :archivo_proyectos

  resources :user_hitos

  resources :user_tareas

  resources :user_listtareas

  resources :user_proyectos

  resources :archivos

  resources :users

  resources :hitos

  resources :tareas

  resources :listtareas

  resources :proyectos

  resources :empresas

  root 'raiz#index'

end

app/models/archivo.rb
class Archivo < ActiveRecord::Base
end

app/models/archivo_hito.rb
class ArchivoHito < ActiveRecord::Base
end

app/models/archivo_proyecto.rb
class ArchivoProyecto < ActiveRecord::Base
end

app/models/archivo_tarea.rb
class ArchivoTarea < ActiveRecord::Base
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
end

app/models/hito.rb
class Hito < ActiveRecord::Base
end

app/models/listtarea.rb
class Listtarea < ActiveRecord::Base
end

app/models/proyecto.rb
class Proyecto < ActiveRecord::Base
end

app/models/tarea.rb
class Tarea < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

	validate :email, presence: true, uniqueness: true


  	has_secure_password
end

app/models/user_hito.rb
class UserHito < ActiveRecord::Base
end

app/models/user_listtarea.rb
class UserListtarea < ActiveRecord::Base
end

app/models/user_proyecto.rb
class UserProyecto < ActiveRecord::Base
end

app/models/user_tarea.rb
class UserTarea < ActiveRecord::Base
end

app/controllers/listtareas_controller.rb
class ListtareasController < ApplicationController
  before_action :set_listtarea, only: [:show, :edit, :update, :destroy]

  # GET /listtareas
  # GET /listtareas.json
  def index
    @listtareas = Listtarea.all
  end

  # GET /listtareas/1
  # GET /listtareas/1.json
  def show
  end

  # GET /listtareas/new
  def new
    @listtarea = Listtarea.new
  end

  # GET /listtareas/1/edit
  def edit
  end

  # POST /listtareas
  # POST /listtareas.json
  def create
    @listtarea = Listtarea.new(listtarea_params)

    respond_to do |format|
      if @listtarea.save
        format.html { redirect_to @listtarea, notice: 'Listtarea was successfully created.' }
        format.json { render :show, status: :created, location: @listtarea }
      else
        format.html { render :new }
        format.json { render json: @listtarea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listtareas/1
  # PATCH/PUT /listtareas/1.json
  def update
    respond_to do |format|
      if @listtarea.update(listtarea_params)
        format.html { redirect_to @listtarea, notice: 'Listtarea was successfully updated.' }
        format.json { render :show, status: :ok, location: @listtarea }
      else
        format.html { render :edit }
        format.json { render json: @listtarea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listtareas/1
  # DELETE /listtareas/1.json
  def destroy
    @listtarea.destroy
    respond_to do |format|
      format.html { redirect_to listtareas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listtarea
      @listtarea = Listtarea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listtarea_params
      params.require(:listtarea).permit(:proyecto_id, :lista, :descripcion, :elista, :lider_id, :falta, :fvcto, :fuce, :fcierre)
    end
end

app/helpers/archivos_helper.rb
module ArchivosHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/hitos_helper.rb
module HitosHelper
end

app/helpers/listtareas_helper.rb
module ListtareasHelper
end

app/helpers/raiz_helper.rb
module RaizHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/tareas_helper.rb
module TareasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/listtareas/_form.html.erb
<%= form_for(@listtarea) do |f| %>
  <% if @listtarea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listtarea.errors.count, "error") %> prohibited this listtarea from being saved:</h2>

      <ul>
      <% @listtarea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :proyecto_id %><br>
    <%= f.number_field :proyecto_id %>
  </div>
  <div class="field">
    <%= f.label :lista %><br>
    <%= f.text_field :lista %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :elista %><br>
    <%= f.text_field :elista %>
  </div>
  <div class="field">
    <%= f.label :lider_id %><br>
    <%= f.number_field :lider_id %>
  </div>
  <div class="field">
    <%= f.label :falta %><br>
    <%= f.datetime_select :falta %>
  </div>
  <div class="field">
    <%= f.label :fvcto %><br>
    <%= f.datetime_select :fvcto %>
  </div>
  <div class="field">
    <%= f.label :fuce %><br>
    <%= f.datetime_select :fuce %>
  </div>
  <div class="field">
    <%= f.label :fcierre %><br>
    <%= f.datetime_select :fcierre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listtareas/edit.html.erb
<h1>Editing listtarea</h1>

<%= render 'form' %>

<%= link_to 'Show', @listtarea %> |
<%= link_to 'Back', listtareas_path %>

app/views/listtareas/index.html.erb
<h1>Listing listtareas</h1>

<table>
  <thead>
    <tr>
      <th>Proyecto</th>
      <th>Lista</th>
      <th>Descripcion</th>
      <th>Elista</th>
      <th>Lider</th>
      <th>Falta</th>
      <th>Fvcto</th>
      <th>Fuce</th>
      <th>Fcierre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listtareas.each do |listtarea| %>
      <tr>
        <td><%= listtarea.proyecto_id %></td>
        <td><%= listtarea.lista %></td>
        <td><%= listtarea.descripcion %></td>
        <td><%= listtarea.elista %></td>
        <td><%= listtarea.lider_id %></td>
        <td><%= listtarea.falta %></td>
        <td><%= listtarea.fvcto %></td>
        <td><%= listtarea.fuce %></td>
        <td><%= listtarea.fcierre %></td>
        <td><%= link_to 'Show', listtarea %></td>
        <td><%= link_to 'Edit', edit_listtarea_path(listtarea) %></td>
        <td><%= link_to 'Destroy', listtarea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listtarea', new_listtarea_path %>

app/views/listtareas/new.html.erb
<h1>New listtarea</h1>

<%= render 'form' %>

<%= link_to 'Back', listtareas_path %>

app/views/listtareas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Proyecto:</strong>
  <%= @listtarea.proyecto_id %>
</p>

<p>
  <strong>Lista:</strong>
  <%= @listtarea.lista %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @listtarea.descripcion %>
</p>

<p>
  <strong>Elista:</strong>
  <%= @listtarea.elista %>
</p>

<p>
  <strong>Lider:</strong>
  <%= @listtarea.lider_id %>
</p>

<p>
  <strong>Falta:</strong>
  <%= @listtarea.falta %>
</p>

<p>
  <strong>Fvcto:</strong>
  <%= @listtarea.fvcto %>
</p>

<p>
  <strong>Fuce:</strong>
  <%= @listtarea.fuce %>
</p>

<p>
  <strong>Fcierre:</strong>
  <%= @listtarea.fcierre %>
</p>

<%= link_to 'Edit', edit_listtarea_path(@listtarea) %> |
<%= link_to 'Back', listtareas_path %>